name: Bug Report
description: File a bug report
title: "[Enter bug title] [release]"
labels: ["bug", "triage"]
assignees:
  - npolly
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! {{title}}
  - type: dropdown
    id: products
    attributes:
      label: What product are you seeing the problem on?
      multiple: false
      options:
        - Allure TestOps
        - Allure plugin
    validations:
      required: true
  - type: input
    id: release
    attributes:
      label: What is the release number?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Also tell us, how did you detected the bug?
      value: |
        1. Go to ...
        2. Click to the button... 
    validations:
      required: true
  - type: textarea
    id: evidencies
    attributes:
      label: Evidencies
      description: Please paste any relevant screenshot or video with bug reproducing.
      placeholder: Paste here your screenshots or video
